### ISSUE TITLE
Add project 3, Convolutional Neural Network implementation using SARS-COV-2 Ct-Scan Dataset

### ISSUE THREAD

**Issue by aniruddh-1** [COVID-19-AI-Research-Project/AI-Classification#7]
**Is your feature proposal related to a problem? Please describe.**
No

**Describe the solution you'd like to implement**
Implementing a CNN model for COVID-19 Detection from a CT Scan Dataset by PlamenLancaster.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by AdamMiltonBarker** [comment]
Thanks @aniruddh-1 please remember to follow the contributing guide exactly. You will need to submit your pull request to branch 0.2.0 which is the current dev branch now.

**Comment by AdamMiltonBarker** [comment]
Hi mate I am going to close this task as I would like to upload the Raspberry Pi 4 project as project 3. I am also going to make project 4 which will be OpenVINO if I can resolve issues with the framework and custom TF 2 models, or an Inception V3 implementation.
